### ISSUE TITLE
Write a test of function parameter by setting spy.

### ISSUE THREAD

**Issue by SifatIbna** [AshfaqKabir/Typescript-Assignment-Nest#4]
https://github.com/AshfaqKabir/Typescript-Assignment-Nest/blob/4957a006be4dc9bd295d080d2423d83b047962b4/src/task-2.ts#L70

**Comment by SifatIbna** [comment]
U should write this test for each function who takes parameters.

**Comment by AshfaqKabir** [comment]
Solved
